### ISSUE TITLE
Consider using a templating engine (Jekyll) along with Markdown

### ISSUE THREAD

**Issue by LaurentGoderre** [w3c/UAAG#2]
Markdown is a convenient format that is very well integrated with GitHub. You could also use jekyll (also integrated with GitHub) to generate the HTML page.

This would allow to have an optimal editing experience for your documents and still getting the same layout for your gh-pages.

**Comment by jspellman** [comment]
Laurent, thanks for the the suggestion, but we have to publish W3C TR documents at the end, and I'm afraid that markdown does not move into HTML without a lot of tweaking at the end.  Plus, we are using a really old format where we split the Master document into two separate files, the Guidelines, and the Reference doc.  That precludes us from using modern spec tools.  :((  The next spec we work on will use better tools, I promise.
